<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>IndustrialPlatform.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IndustrialPlatform.Application\IndustrialPlatform.Application.csproj" />
    <ProjectReference Include="..\IndustrialPlatform.Domain\IndustrialPlatform.Domain.csproj" />
    <ProjectReference Include="..\IndustrialPlatform.Shared\IndustrialPlatform.Shared.csproj" />
  </ItemGroup>

</Project>
